######
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'


- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: k8sauth
    #acrdevurl: 'k8sauth.azurecr.io'
    #replicaNo: 3
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS124
    environment: 'k8sdev.default'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acrsecret)'
              dockerRegistryEndpoint: 'ResourceTest'          
              
          - task: KubernetesManifest@1
            inputs:
              action: deploy
              connectionType: azureResourceManager
              azureSubscriptionConnection: Azure subscription 1(651da490-bde4-40b0-a1ae-aa4995df490c)
              azureResourceGroup: resource-test
              kubernetesCluster: Aks124
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
            

